### ISSUE TITLE
Why should we use the transposed DTI score matrices to calculate the loss score?

### ISSUE THREAD

**Issue by WuSht** [JackieSun818/AEFS#1]
It is the third term in Equation (7) in the article.

**Comment by JackieSun818** [comment]
> 这是本文方程(7)中的第三个项。

Each row in DTI matrix represents the targets of a drug, which can be seen as the function of the drug.  Also, each column of DTI matrix contains the interacted drugs of a target, which can be seen as the function of the target. As mentioned in the paper, we hope to keep the correlations between the proteins in the drug space, so we transposed the DTI matrix to get the functional information of proteins.

**Comment by WuSht** [comment]
Brilliant work, and thank you very much!
